name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Patch Gradle files for plugins
        run: |
          find $PUB_CACHE/hosted/pub.dev -path "*/android/build.gradle" | while read gradle_file; do
            echo "Patching $gradle_file"
            # Add compileSdk if not present
            if ! grep -q "compileSdk" "$gradle_file"; then
              sed -i '/android {/a\    compileSdk 34' "$gradle_file"
            fi
            # Add Java/Kotlin target configs if missing
            if ! grep -q "kotlinOptions" "$gradle_file"; then
              sed -i '/android {/a\    compileOptions {\n        sourceCompatibility JavaVersion.VERSION_17\n        targetCompatibility JavaVersion.VERSION_17\n    }\n\n    kotlinOptions {\n        jvmTarget = "17"\n    }' "$gradle_file"
            fi
          done

      - name: Build release APK
        run: flutter build apk --release
