name: Build Flutter APK

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Ensure platforms exist
        run: flutter create .

      - name: Install dependencies
        run: flutter pub get

      - name: Patch Gradle files (Kotlin + JVM target)
        run: |
          # Update Kotlin version
          find $HOME/.pub-cache -type f -name build.gradle \
            -exec sed -i 's/ext.kotlin_version *= *.*/ext.kotlin_version = "1.9.24"/' {} \;

          # Fix JVM target mismatches
          find $HOME/.pub-cache -type f -name build.gradle | while read file; do
            awk 'BEGIN{added=0}
              {print}
              /^android[ \t]*\{/ && added==0 {
                print "    compileOptions {"
                print "        sourceCompatibility JavaVersion.VERSION_17"
                print "        targetCompatibility JavaVersion.VERSION_17"
                print "    }"
                print "    kotlinOptions { jvmTarget = \"17\" }"
                print "    java { toolchain { languageVersion.set(JavaLanguageVersion.of(17)) } }"
                added=1
              }' "$file" > tmp && mv tmp "$file"
          done

      - name: Flutter clean
        run: flutter clean

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release*.apk

      - name: Create GitHub Release (on tags)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
