name: Build Flutter APK

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (Gradle requires this)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Ensure platforms exist
        run: flutter create .

      - name: Install dependencies
        run: flutter pub get

      - name: Patch Gradle files for plugins
        run: |
          # 1. Update Kotlin version everywhere
          find $HOME/.pub-cache -type f -name build.gradle \
            -exec sed -i 's/ext.kotlin_version *= *.*/ext.kotlin_version = "1.9.24"/' {} \;

          # 2. Add compileSdkVersion & Toolchain inside android {} blocks
          find $HOME/.pub-cache -type f -name build.gradle \
            -exec sh -c 'awk "BEGIN{added=0} {pr
