name: Build Flutter APK

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]      # v1.0.0, v1.0.1, etc. will trigger a Release
  pull_request:
  workflow_dispatch:     # allows manual runs from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (Gradle requires this)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # optionally pin a version, e.g. flutter-version: '3.22.3'
          cache: true

      - name: Flutter version
        run: flutter --version

      # Generates missing android/ios folders if not present
      - name: Ensure platforms exist
        run: flutter create .

      - name: Install dependencies
        run: flutter pub get
        
      - name: Patch Gradle files for plugins
        run: |
          # Update Kotlin version everywhere
          find $HOME/.pub-cache -type f -name build.gradle -exec sed -i 's/ext.kotlin_version *= *.*/ext.kotlin_version = "1.9.24"/' {} +

          # Add compileSdkVersion 34 to google_mobile_ads plugin
          find $HOME/.pub-cache -path "*/google_mobile_ads-*/android/build.gradle" -exec awk 'BEGIN{added=0} {print} /^android[ \t]*\{/ && added==0 {print "    compileSdkVersion 34"; added=1}' {} > tmp && mv tmp {} \;

          # Force Java 17 & Kotlin JVM target 17 everywhere
          find $HOME/.pub-cache -type f -name build.gradle -exec awk 'BEGIN{added=0} {print} /^android[ \t]*\{/ && added==0 {print "    compileOptions {\n        sourceCompatibility JavaVersion.VERSION_17\n        targetCompatibility JavaVersion.VERSION_17\n    }\n\n    kotlinOptions {\n        jvmTarget = \"17\"\n    }"; added=1}' {} > tmp && mv tmp {} \;

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release*.apk

      - name: Create GitHub Release (on tags)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

