name: Flutter Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      # 3️⃣ Install Java 17 (matches Kotlin 17 target)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4️⃣ Get Flutter dependencies
      - name: Get dependencies
        run: flutter pub get

      # 5️⃣ Patch Gradle files for JVM target & compileSdkVersion
      - name: Patch Flutter plugins
        run: |
          echo "Patching all plugins to use Java 17 and compileSdkVersion 34..."
          
          # Apply compileOptions for Java 17 to all Gradle files in plugins
          find $HOME/.pub-cache -path "*/android/build.gradle" | while read gradleFile; do
            if ! grep -q "compileOptions" "$gradleFile"; then
              sed -i '/android {/a\
    compileOptions {\
        sourceCompatibility JavaVersion.VERSION_17\
        targetCompatibility JavaVersion.VERSION_17\
    }' "$gradleFile"
            fi
          done

          # Patch google_mobile_ads specifically
          ADS_GRADLE_FILE=$(find $HOME/.pub-cache -path "*/google_mobile_ads-*/android/build.gradle" | head -n 1)
          if [ -f "$ADS_GRADLE_FILE" ]; then
            echo "Patching $ADS_GRADLE_FILE"

            # Add compileSdkVersion if missing
            if ! grep -q "compileSdkVersion" "$ADS_GRADLE_FILE"; then
              sed -i '/android {/a\    compileSdkVersion 34' "$ADS_GRADLE_FILE"
            fi

            # Add Kotlin JVM target if missing
            if ! grep -q "kotlinOptions" "$ADS_GRADLE_FILE"; then
              cat <<'EOF' >> "$ADS_GRADLE_FILE"

afterEvaluate {
    if (project.hasProperty("android")) {
        android {
            kotlinOptions {
                jvmTarget = "17"
            }
        }
    }
}
EOF
            fi
          else
            echo "google_mobile_ads build.gradle not found!"
          fi

      # 6️⃣ Build the APK
      - name: Build release APK
        run: flutter build apk --release

      # 7️⃣ Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
