name: Flutter Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3" # You can set to stable if needed

      # 3️⃣ Install Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # 4️⃣ Get dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # 5️⃣ Patch Gradle files for JVM target & compileSdkVersion
      - name: Patch F
